"""Updated ChatHistory model with new columns

Revision ID: 373ee4b20ef7
Revises: 
Create Date: 2024-07-06 15:12:31.883937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '373ee4b20ef7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('predicted_intent', sa.String(length=120)))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.drop_column('predicted_intent')
        batch_op.drop_column('feedback')

    # ### end Alembic commands ###
